version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data/${ENV}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: testdb
      POSTGRES_PASSWORD: testpassword